---
name: "rabbitmq.hypervisor.reboot.rule"
pack: "stackstorm_openstack"
description: "Handles incoming trigger \"rabbit_reply_message\" with message_type HYPERVISOR_REBOOT"
enabled: true
trigger:
    type: stackstorm_send_notifications.rabbit_reply_message

criteria:
    trigger.message_type:
        type: "iequals"
        pattern: "HYPERVISOR_REBOOT"

action:
    ref: stackstorm_send_notifications.rabbit.execute.and.reply
    parameters:
        action_inputs: "{{ trigger.args }}"
        dynamic_action: "stackstorm_openstack.hypervisor.reboot"
        routing_key: "{{trigger.routing_key}}"
        exchange: ""